# Generated by Django 4.1.6 on 2023-02-14 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('key', models.CharField(max_length=20, verbose_name='Ключ проекта')),
                ('id_project_in_jira', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('rank', models.CharField(max_length=30, verbose_name='Уровень')),
                ('email', models.CharField(max_length=100, verbose_name='Эл.Почта')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('key', models.CharField(max_length=20, verbose_name='Ключ')),
                ('time_original_estimate', models.IntegerField(verbose_name='Оценочное время на выполнение (сек)')),
                ('duedate', models.DateField(verbose_name='Дедлайн')),
                ('start_date', models.DateField(verbose_name='Дата начала работы над задачей')),
                ('deleted', models.DateField()),
                ('description', models.CharField(max_length=3000, verbose_name='Описание')),
                ('id_task_in_jira', models.IntegerField()),
                ('date_create', models.DateField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_test_django.worker', verbose_name='Исполнитель')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_id', to='my_test_django.worker', verbose_name='Автор')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_test_django.project', verbose_name='Проект')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_test_django.worker', verbose_name='Руководитель'),
        ),
    ]
